name: eggnstone_flutter_meta
copyright: 2019-2024 Mark Eggenstein
description: Native design with ease
version: 0.4.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  eggnstone_dart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
