name: eggnstone_flutter_meta
copyright: 2019-2024 Mark Eggenstein
description: Native design with ease
version: 0.3.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
