name: eggnstone_flutter_meta
copyright: 2019-2024 Mark Eggenstein
description: Native design with ease
version: 0.3.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #
