name: eggnstone_flutter_meta
copyright: 2019-2025 Mark Eggenstein
description: Native design with ease.
version: 0.4.6

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  eggnstone_dart: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
