name: eggnstone_flutter_meta
author: Mark Eggenstein
copyright: 2019-2020 Mark Eggenstein
description: Native design with ease
version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
