name: widgetbook_workspace
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  eggnstone_flutter_meta:
    path: ../
  widgetbook: ^3.10.2
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  widgetbook_generator: ^3.9.1

flutter:
  uses-material-design: true
